= Vert.x Troubleshooting

This project is a template to start your own Vert.x project using Apache Maven.

== Prerequisites

* Apache Maven
* JDK 8+

== WebClient vs. HttpClient

This project is for troubleshooting the differences between Vert.x's WebClient and HttpClient.

[source]
----
git clone https://github.com/jeremyrdavis/vertx-troubleshooting.git
----

== Running the project

Once you have retrieved the project, you can check that everything works (it doesn't work at the moment) with:

[source]
----
mvn test exec:java
----

The command compiles the project and runs the tests, which fail at the moment.

== Anatomy of the project

The project contains:

* a `pom.xml` file
* a _main_ verticle file (src/main/java/io/vertx/starter/MainVerticle.java)
* an unit test (src/main/test/io/vertx/starter/MainVerticleTest.java)

=== MainVerticle

MainVerticle creates an HttpServer and resturns, "Hello, Vert.x!"

=== MainVerticleTest

MainVerticleTest contains 2 methods: testWithHttpClient and testWithWebClient.  Both deploy MainVerticle and then call the root url.

The testWithWebClient works while the testWithHttpClient hangs and eventually times out.
